In [1]:
import pandas as pd

df = pd.read_csv("Historical Product Demand.csv")

In [2]:
df.head()

   Product_Code Warehouse Product_Category       Date Order_Demand
0  Product_0993    Whse_J     Category_028  2012/7/27         100
1  Product_0979    Whse_J     Category_028  2012/1/19         500
2  Product_0979    Whse_J     Category_028   2012/2/3         500
3  Product_0979    Whse_J     Category_028   2012/2/9         500
4  Product_0979    Whse_J     Category_028   2012/3/2         500

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 5 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   Product_Code      1048575 non-null  str
 1   Warehouse         1048575 non-null  str
 2   Product_Category  1048575 non-null  str
 3   Date              1037336 non-null  str
 4   Order_Demand      1048575 non-null  str
dtypes: str(5)
memory usage: 40.0 MB

In [4]:
df.isnull().sum()

Product_Code            0
Warehouse               0
Product_Category        0
Date                11239
Order_Demand            0
dtype: int64

In [5]:
df.describe()

        Product_Code Warehouse Product_Category       Date Order_Demand
count        1048575   1048575          1048575    1037336      1048575
unique          2160         4               33       1729         3828
top     Product_1359    Whse_J     Category_019  2013/9/27        1000
freq           16936    764447           481099       2075       112682

In [6]:
df.duplicated().sum()
df.drop_duplicates(inplace=True)

In [7]:
df.sample(5)

         Product_Code Warehouse Product_Category        Date Order_Demand
98264    Product_1377    Whse_J     Category_019   2012/7/10        3000
844123   Product_0390    Whse_S     Category_030   2015/3/19        1000
275591   Product_0063    Whse_S     Category_019   2013/12/2        1000
506904   Product_1969    Whse_J     Category_005  2014/12/25         500
1029460  Product_0399    Whse_J     Category_030  2016/11/17         100

In [8]:
df['Date'] = pd.to_datetime(df['Date'])

In [9]:
df.info()

<class 'pandas.DataFrame'>
Index: 926152 entries, 0 to 1048574
Data columns (total 5 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Product_Code      926152 non-null  str
 1   Warehouse         926152 non-null  str
 2   Product_Category  926152 non-null  str
 3   Date              924272 non-null  datetime64[us]
 4   Order_Demand      926152 non-null  str
dtypes: datetime64[us](1), str(4)
memory usage: 42.4 MB

In [10]:
df['Order_Demand'] = pd.to_numeric(df['Order_Demand'], errors='coerce')

print("NaN in Order_Demand" , df["Order_Demand"].isnull().sum())
print("NaN in Date" , df["Date"].isnull().sum())

NaN in Order_Demand 6798
NaN in Date 1880

In [12]:
df.dropna(subset=['Date'], inplace=True)